//! Definition of the top-level BLF log object enum.

use crate::objects::{
    can::*, lin::*, flexray::*, ethernet::*, app_events::*, env_vars::*, most::*
};

/// An enumeration of all possible log objects that can be parsed from a BLF file.
#[derive(Debug, Clone, PartialEq)]
pub enum LogObject {
    CanMessage(CanMessage),
    CanMessage2(CanMessage2),
    CanErrorFrame(CanErrorFrame),
    CanFdMessage(CanFdMessage),
    CanFdMessage64(CanFdMessage64),
    CanOverloadFrame(CanOverloadFrame),
    CanDriverStatistic(CanDriverStatistic),
    CanDriverError(CanDriverError),
    LinMessage(LinMessage),
    LinMessage2(LinMessage2),
    LinCrcError(LinCrcError),
    LinDlcInfo(LinDlcInfo),
    LinReceiveError(LinReceiveError),
    LinSendError(LinSendError),
    LinSlaveTimeout(LinSlaveTimeout),
    LinSchedulerModeChange(LinSchedulerModeChange),
    LinSyncError(LinSyncError),
    LinBaudrateEvent(LinBaudrateEvent),
    LinSleepModeEvent(LinSleepModeEvent),
    LinWakeupEvent(LinWakeupEvent),
    FlexRayData(FlexRayData),
    FlexRaySync(FlexRaySync),
    FlexRayV6Message(FlexRayV6Message),
    FlexRayV6StartCycleEvent(FlexRayV6StartCycleEvent),
    FlexRayStatusEvent(FlexRayStatusEvent),
    FlexRayVFrError(FlexRayVFrError),
    FlexRayVFrStatus(FlexRayVFrStatus),
    FlexRayVFrStartCycle(FlexRayVFrStartCycle),
    FlexRayVFrReceiveMsg(FlexRayVFrReceiveMsg),
    FlexRayVFrReceiveMsgEx(FlexRayVFrReceiveMsgEx),
    EthernetFrame(EthernetFrame),
    AppTrigger(AppTrigger),
    EventComment(EventComment),
    GlobalMarker(GlobalMarker),
    SystemVariable(SystemVariable),
    EnvInteger(EnvInteger),
    EnvDouble(EnvDouble),
    EnvString(EnvString),
    MostSpy(MostSpy),
    MostCtrl(MostCtrl),
    MostPkt2(MostPkt2),
    MostLightLock(MostLightLock),
    MostStatistic(MostStatistic),
    MostHwMode(MostHwMode),
    MostReg(MostReg),
    MostGenReg(MostGenReg),
    MostNetState(MostNetState),
    MostDataLost(MostDataLost),
    MostTrigger(MostTrigger),
}
