//! Defines the ObjectType enum for BLF log objects.

/// Represents the type of a BLF log object.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
#[repr(u32)]
pub enum ObjectType {
    /// Unknown object
    Unknown = 0,
    CanMessage = 1,
    CanError = 2,
    CanOverload = 3,
    CanStatistic = 4,
    AppTrigger = 5,
    EnvInteger = 6,
    EnvDouble = 7,
    EnvString = 8,
    LogContainer = 10,
    LinMessage = 11,
    LinCrcError = 12,
    LinDlcInfo = 13,
    LinReceiveError = 14,
    LinSendError = 15,
    LinSlaveTimeout = 16,
    LinSchedulerModeChange = 17,
    LinSyncError = 18,
    LinBaudrate = 19,
    LinSleep = 20,
    LinWakeup = 21,
    MostSpy = 22,
    MostCtrl = 23,
    MostLightLock = 24,
    MostStatistic = 25,
    FlexRayData = 29,
    FlexRaySync = 30,
    CanDriverError = 31,
    MostPkt = 32,
    MostPkt2 = 33,
    MostHwMode = 34,
    MostReg = 35,
    MostGenReg = 36,
    MostNetState = 37,
    MostDataLost = 38,
    MostTrigger = 39,
    FlexRayMessage = 41,
    LinMessage2 = 57,
    EthernetFrame = 71,
    SystemVariable = 72,
    CanMessage2 = 86,
    EventComment = 92,
    GlobalMarker = 96,
    CanFdMessage = 100,
    CanFdMessage64 = 101,
}

impl From<u32> for ObjectType {
    fn from(val: u32) -> Self {
        match val {
            1 => ObjectType::CanMessage,
            2 => ObjectType::CanError,
            3 => ObjectType::CanOverload,
            4 => ObjectType::CanStatistic,
            5 => ObjectType::AppTrigger,
            6 => ObjectType::EnvInteger,
            7 => ObjectType::EnvDouble,
            8 => ObjectType::EnvString,
            10 => ObjectType::LogContainer,
            11 => ObjectType::LinMessage,
            12 => ObjectType::LinCrcError,
            13 => ObjectType::LinDlcInfo,
            14 => ObjectType::LinReceiveError,
            15 => ObjectType::LinSendError,
            16 => ObjectType::LinSlaveTimeout,
            17 => ObjectType::LinSchedulerModeChange,
            18 => ObjectType::LinSyncError,
            19 => ObjectType::LinBaudrate,
            20 => ObjectType::LinSleep,
            21 => ObjectType::LinWakeup,
            22 => ObjectType::MostSpy,
            23 => ObjectType::MostCtrl,
            24 => ObjectType::MostLightLock,
            25 => ObjectType::MostStatistic,
            29 => ObjectType::FlexRayData,
            30 => ObjectType::FlexRaySync,
            31 => ObjectType::CanDriverError,
            32 => ObjectType::MostPkt,
            33 => ObjectType::MostPkt2,
            34 => ObjectType::MostHwMode,
            35 => ObjectType::MostReg,
            36 => ObjectType::MostGenReg,
            37 => ObjectType::MostNetState,
            38 => ObjectType::MostDataLost,
            39 => ObjectType::MostTrigger,
            41 => ObjectType::FlexRayMessage,
            57 => ObjectType::LinMessage2,
            71 => ObjectType::EthernetFrame,
            72 => ObjectType::SystemVariable,
            86 => ObjectType::CanMessage2,
            92 => ObjectType::EventComment,
            96 => ObjectType::GlobalMarker,
            100 => ObjectType::CanFdMessage,
            101 => ObjectType::CanFdMessage64,
            _ => ObjectType::Unknown,
        }
    }
}
